services:
  - type: web
    name: study-buddy-frontend
    env: docker
    dockerfilePath: ./frontend/Dockerfile
    plan: free
    envVars:
      - key: NODE_ENV
        value: production

  - type: web
    name: study-buddy-backend
    env: docker
    dockerfilePath: ./backend/Dockerfile
    plan: free
    envVars:
      - key: NODE_ENV
        value: production